services:
  api-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    environment:
      DATABASE_URL: postgres://user:password@postgres_text:5432/pastebin_text
      REDIS_URL_TEXT: redis://redis_text/0
      REDIS_URL_HASH: redis://redis_hash/0
    depends_on:
      - postgres_text
      - redis_text
      - redis_hash
    ports:
      - "8001:8001"
    networks:
      - main_network

  hash-service:
    build:
      context: ./hash_service
      dockerfile: Dockerfile
    container_name: hash_service
    environment:
      DATABASE_URL: postgres://user:password@postgres_text:5432/pastebin_text
      REDIS_URL_HASH: redis://redis_hash/0
    depends_on:
      - postgres_text
      - redis_hash
    ports:
      - "8002:8002"
    networks:
      - main_network

  redis_text:
    image: redis:7.2-alpine
    container_name: redis_text
    restart: always
    networks:
      - main_network

  redis_hash:
    image: redis:7.2-alpine
    container_name: redis_hash
    restart: always
    networks:
      - main_network

  postgres_text:
    image: postgres:16-alpine
    container_name: postgres_text
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastebin_text
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - main_network

volumes:
  pg_data:
    driver: local

networks:
  main_network:
    driver: bridge