services:
  api-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    environment:
      DATABASE_URL: postgres://user:password@postgres_text:5432/pastebin_text
      REDIS_URL_TEXT: redis://redis-text:6379/0
      REDIS_URL_HASH: redis://redis-hash:6380/0
    depends_on:
      - postgres_text
      - redis-text
      - redis-hash
    ports:
      - "8001:8001"
    networks:
      - main_network

  redis-text:
    image: redis:7.2-alpine
    container_name: redis_text
    restart: always
    ports:
      - "6379:6379"
    networks:
      - main_network

  redis-hash:
    image: redis:7.2-alpine
    container_name: redis_hash
    restart: always
    ports:
      - "6380:6380"
    networks:
      - main_network

  postgres_text:
    image: postgres:16-alpine
    container_name: postgres_text
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastebin_text
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - main_network

volumes:
  pg_data:
    driver: local

networks:
  main_network:
    driver: bridge