global:
  scrape_interval: 15s  # интервал сбора метрик

scrape_configs:
  - job_name: 'api-service'
    static_configs:
      - targets: ['api-service:8001']

  - job_name: 'hash-service'
    static_configs:
      - targets: ['hash-service:8002']
