global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]

  - job_name: "api"
    static_configs:
      - targets: ["api:8000"]

  - job_name: "hash-generator"
    static_configs:
      - targets: ["hash-generator:8001"]
